### ISSUE TITLE
It Can't pack some file

### ISSUE THREAD

**Issue by CGMentos** [jackson-c/quickpack#3]
> Forgive my broken english.

Your tool its really good , but still have some defect.
Like it can't packup:

-  .kv file`(*\csgo\maps\mapname.kv)`
-  radar file`(*\csgo\resource\overviews\mapname.txt)`
`(*\csgo\resource\overviews\mapname_radar.dds)`
`(*\csgo\resource\overviews\mapname_radar_spectate.dds)`
`(*\csgo\resource\overviews\mapname_lower_radar.dds)`
`(*\csgo\resource\overviews\mapname_higher_radar.dds)`

Hope you can make 'quickpack' more closer in 'perfect'
Have a nice day 😄

**Comment by cannon** [comment]
Thanks for your report, I will look into adding these files automatically. In the meantime, you can use a whitelist to force these to be packed as the readme explains

**Comment by cannon** [comment]
I've added these and a few other things in my latest version. Thanks!
