### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by aurowora** [jackson-c/quickpack#5]
This may just be because of the size of the map I'm trying to pack, but python seems to run out of memory while the program is running.

The program creates its temp directory, then appears to be working for a couple minutes, then it crashes with the MemoryError.

Here is the full output of the script:

QuickPack v1.41 by Jackson Cannon - https://github.com/cannon/quickpack

Reading br_testmap.bsp...
Traceback (most recent call last):
  File "QuickPack.py", line 472, in <module>
    main()
  File "QuickPack.py", line 112, in main
    read_staticprop_lump(bsp_file)
  File "QuickPack.py", line 399, in read_staticprop_lump
    prop = readcstr(bsp_file)
  File "QuickPack.py", line 190, in readcstr
    return ''.join(itertools.takewhile('\0'.__ne__, toeof))
MemoryError

Thanks.

EDIT: The map file itself is about 24 megabytes and the sum of the materials that need packing are around 200 MB.

**Comment by aurowora** [comment]
Seems my path was set to run the script with python 3 for whatever reason, I'll try with 2.7 when I get home.

**Comment by cannon** [comment]
I added a quick python version check, thanks
