### ISSUE TITLE
QuickPack throws a KeyError and stops

### ISSUE THREAD

**Issue by myuce** [jackson-c/quickpack#6]
![screenshot](https://user-images.githubusercontent.com/4535623/39158662-f9535f90-4769-11e8-90cf-cdfd30be5efc.png)
 
As it can be seen in the screenshot, QuickPack stops packing the assets and stops working. Any ideas how I can fix that?

**Comment by cannon** [comment]
I think this was caused by somehow requiring a model that isn't used in a prop, so the program doesn't know what skins to include. I patched it to just include all skins in this case. Thanks for reporting, let me know if you have more issues!
