### ISSUE TITLE
miss packing vtf file in this kind of vmt

### ISSUE THREAD

**Issue by chenbuyi2019** [jackson-c/quickpack#8]
the vmt:
`VertexLitGeneric
{
$baseTexture "models/props_urban/porch_light001.vtf"
}
`
the vtf is not packed in bsp, i think the problem is our script can't parse "xx.vtf".
can you fix this?

**Comment by cannon** [comment]
Is that a working VMT? I think you're supposed to not have .vtf

**Comment by chenbuyi2019** [comment]
> 
> 
> Is that a working VMT? I think you're supposed to not have .vtf

Yes,it is a working vmt and the vtf file exists.
You can have a try on your PC. Edit one vmt, insert ".vtf" after the texture name.

**Comment by cannon** [comment]
Fixed it, thanks
